In [4]:
import pandas as pd
import numpy as np

In [5]:
data = [1,2,3,4,5,6]
s=pd.Series(data)
print(s)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [6]:
data1 = (1,2,3,4,5,6)
s1 = pd.Series(data1)
print(s1)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [7]:
data2 = {'A':1,'B':2 ,'C':3}
s2 = pd.Series(data2)
print(s2)

A    1
B    2
C    3
dtype: int64

In [8]:
S1 =pd.Series(data2,index=['A' ,'B' , 'C' ,'D' , 'E'])
print(S1)

A    1.0
B    2.0
C    3.0
D    NaN
E    NaN
dtype: float64

In [9]:
arr = np.array([1,2,3,4,5])
s = pd.Series(arr)
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int32

In [10]:
arr = np.array([1,2,3,4,5])
s = pd.Series(arr,dtype='float')
print(s)

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
dtype: float64

In [13]:

s = pd.Series(5,index=[0,1,2,3])
print(s)

0    5
1    5
2    5
3    5
dtype: int64

In [14]:
s = pd.Series(5,index=[0,1,2,3],name="Number")
print(s)

0    5
1    5
2    5
3    5
Name: Number, dtype: int64

In [15]:
s = pd.Series([10,20,30,40,50],index=['A' , 'B' , 'C' , 'D' , 'E'],name="Number")
print(s)

A    10
B    20
C    30
D    40
E    50
Name: Number, dtype: int64

In [16]:
print(s.values)

[10 20 30 40 50]

In [17]:
print(s.index)

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')

In [19]:
print(s.ndim)

1

In [20]:
print(s.size)

5

In [21]:
print(s.name)

Number

In [22]:
print(s.shape)

(5,)

In [23]:
print(s.is_unique)

True

In [24]:
print(s.min())

10

In [25]:
print(s.max())

50

In [30]:
data = [10,20,30,40,50,60]
s = pd.Series(data,index=['A','B','C','D','E','F'])

print(s.loc['B'])

20

In [32]:
data = [10,20,30,40,50,60]
s = pd.Series(data,index=['A','B','C','D','E','F'])

print(s.loc['B':'E'])

B    20
C    30
D    40
E    50
dtype: int64

In [38]:
data = [10,20,30,40,50,60]
s = pd.Series(data,index=['A','B','C','D','E','F'])

print(s.iloc[2])
print(s.iloc[[3,5]])

30
D    40
F    60
dtype: int64

In [39]:
s = pd.Series([10,20,30,40,50],index=['A' , 'B' , 'C' , 'D' , 'E'],name="Number")
print(s)

A    10
B    20
C    30
D    40
E    50
Name: Number, dtype: int64

In [40]:
s.loc["B"]

20

In [41]:
data11=s.loc['B']=70
print(data11)

70

In [42]:
print(s)

A    10
B    70
C    30
D    40
E    50
Name: Number, dtype: int64

In [47]:
dd= s.values>30

In [48]:
print(dd)

[False  True False  True  True]

In [59]:
s1 = pd.DataFrame({"ID":[10,20,30,40,50],"Name":['A' , 'B' , 'C' , 'D' , 'E'],"Marks":[70,65,45,67,45]} , index=None)
print(s1)

   ID Name  Marks
0  10    A     70
1  20    B     65
2  30    C     45
3  40    D     67
4  50    E     45

In [27]:
import pandas as pd
import numpy as np
df=pd.DataFrame({"Name":["Dhoni","Rohit","Virat","Gill"],"Run":[12000,11000,3000,4000],"Average":[59.5,48.7,51.2,45.3]},index=["A","B","C","D"])
print(df.shape)
print(df.size)
print(df.values)
print(df["Name"])
print(df)
print(df.loc['B':'D'])
df.loc['C','Run']=4000
print(df)
df.set_index('Name')
df.set_index(['Name','Run'],drop=True)

(4, 3)
12
[['Dhoni' 12000 59.5]
 ['Rohit' 11000 48.7]
 ['Virat' 3000 51.2]
 ['Gill' 4000 45.3]]
A    Dhoni
B    Rohit
C    Virat
D     Gill
Name: Name, dtype: object
    Name    Run  Average
A  Dhoni  12000     59.5
B  Rohit  11000     48.7
C  Virat   3000     51.2
D   Gill   4000     45.3
    Name    Run  Average
B  Rohit  11000     48.7
C  Virat   3000     51.2
D   Gill   4000     45.3
    Name    Run  Average
A  Dhoni  12000     59.5
B  Rohit  11000     48.7
C  Virat   4000     51.2
D   Gill   4000     45.3

             Average
Name  Run
Dhoni 12000     59.5
Rohit 11000     48.7
Virat 4000      51.2
Gill  4000      45.3

In [28]:
df.reset_index()

  index   Name    Run  Average
0     A  Dhoni  12000     59.5
1     B  Rohit  11000     48.7
2     C  Virat   4000     51.2
3     D   Gill   4000     45.3

In [32]:
df.sort_values(by='Average',ascending=False,axis=0)

    Name    Run  Average
A  Dhoni  12000     59.5
C  Virat   4000     51.2
B  Rohit  11000     48.7
D   Gill   4000     45.3

In [36]:
df.sort_index(axis=1)

   Average   Name    Run
A     59.5  Dhoni  12000
B     48.7  Rohit  11000
C     51.2  Virat   4000
D     45.3   Gill   4000

In [41]:
df['score']=[1000,3000,5000,7000]
d=pd.DataFrame(df,index=['A','B','C','D'])
print(d)

    Name    Run  Average  score
A  Dhoni  12000     59.5   1000
B  Rohit  11000     48.7   3000
C  Virat   4000     51.2   5000
D   Gill   4000     45.3   7000

In [43]:
df[(df['Run']>1000)&(df['Average']>50)]

    Name    Run  Average  score
A  Dhoni  12000     59.5   1000
C  Virat   4000     51.2   5000

In [54]:
df['Name'][(df['Average']>50)]
df[['Name','Average']][(df['Average']>50)]
df.sort_values(by=['Run','Average'],ascending=[True,False],ignore_index=True,inplace=False)

    Name    Run  Average  score
0  Virat   4000     51.2   5000
1   Gill   4000     45.3   7000
2  Rohit  11000     48.7   3000
3  Dhoni  12000     59.5   1000

In [57]:
import pandas as pd
import numpy as np
df=pd.read_csv('auto-mpg.csv')
df.shape

3582

In [58]:
df.size

3582

In [59]:
df.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model year', 'origin', 'car name'],
      dtype='object')

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    object
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64
 7   origin        398 non-null    int64
 8   car name      398 non-null    object
dtypes: float64(3), int64(4), object(2)
memory usage: 28.1+ KB

In [66]:
df.sample()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
134,16.0,6,258.0,110,3632,18.0,74,1,amc matador

In [67]:
df.head(10)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
5,15.0,8,429.0,198,4341,10.0,70,1,ford galaxie 500
6,14.0,8,454.0,220,4354,9.0,70,1,chevrolet impala
7,14.0,8,440.0,215,4312,8.5,70,1,plymouth fury iii
8,14.0,8,455.0,225,4425,10.0,70,1,pontiac catalina
9,15.0,8,390.0,190,3850,8.5,70,1,amc ambassador dpl

In [69]:
df.tail(15)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
383,38.0,4,91.0,67,1965,15.0,82,3,honda civic
384,32.0,4,91.0,67,1965,15.7,82,3,honda civic (auto)
385,38.0,4,91.0,67,1995,16.2,82,3,datsun 310 gx
386,25.0,6,181.0,110,2945,16.4,82,1,buick century limited
387,38.0,6,262.0,85,3015,17.0,82,1,oldsmobile cutlass ciera (diesel)
388,26.0,4,156.0,92,2585,14.5,82,1,chrysler lebaron medallion
389,22.0,6,232.0,112,2835,14.7,82,1,ford granada l
390,32.0,4,144.0,96,2665,13.9,82,3,toyota celica gt
391,36.0,4,135.0,84,2370,13.0,82,1,dodge charger 2.2
392,27.0,4,151.0,90,2950,17.3,82,1,chevrolet camaro
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [70]:
df.describe()

,mpg,cylinders,displacement,weight,acceleration,model year,origin
count,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000
mean,23.514573,5.454774,193.425879,2970.424623,15.568090,76.010050,1.572864
std,7.815984,1.701004,104.269838,846.841774,2.757689,3.697627,0.802055
min,9.000000,3.000000,68.000000,1613.000000,8.000000,70.000000,1.000000
25%,17.500000,4.000000,104.250000,2223.750000,13.825000,73.000000,1.000000
50%,23.000000,4.000000,148.500000,2803.500000,15.500000,76.000000,1.000000
75%,29.000000,8.000000,262.000000,3608.000000,17.175000,79.000000,2.000000
max,46.600000,8.000000,455.000000,5140.000000,24.800000,82.000000,3.000000

In [73]:
df.describe(include='all')

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
count,398.000000,398.000000,398.000000,398,398.000000,398.000000,398.000000,398.000000,398
unique,NaN,NaN,NaN,94,NaN,NaN,NaN,NaN,305
top,NaN,NaN,NaN,150,NaN,NaN,NaN,NaN,ford pinto
freq,NaN,NaN,NaN,22,NaN,NaN,NaN,NaN,6
mean,23.514573,5.454774,193.425879,NaN,2970.424623,15.568090,76.010050,1.572864,NaN
std,7.815984,1.701004,104.269838,NaN,846.841774,2.757689,3.697627,0.802055,NaN
min,9.000000,3.000000,68.000000,NaN,1613.000000,8.000000,70.000000,1.000000,NaN
25%,17.500000,4.000000,104.250000,NaN,2223.750000,13.825000,73.000000,1.000000,NaN
50%,23.000000,4.000000,148.500000,NaN,2803.500000,15.500000,76.000000,1.000000,NaN
75%,29.000000,8.000000,262.000000,NaN,3608.000000,17.175000,79.000000,2.000000,NaN
max,46.600000,8.000000,455.000000,NaN,5140.000000,24.800000,82.000000,3.000000,NaN

In [74]:
df.describe(exclude='int64')

               mpg  displacement horsepower  acceleration    car name
count   398.000000    398.000000        398    398.000000         398
unique         NaN           NaN         94           NaN         305
top            NaN           NaN        150           NaN  ford pinto
freq           NaN           NaN         22           NaN           6
mean     23.514573    193.425879        NaN     15.568090         NaN
std       7.815984    104.269838        NaN      2.757689         NaN
min       9.000000     68.000000        NaN      8.000000         NaN
25%      17.500000    104.250000        NaN     13.825000         NaN
50%      23.000000    148.500000        NaN     15.500000         NaN
75%      29.000000    262.000000        NaN     17.175000         NaN
max      46.600000    455.000000        NaN     24.800000         NaN

In [75]:
df.describe(include=['int64','float'])

,mpg,cylinders,displacement,weight,acceleration,model year,origin
count,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000
mean,23.514573,5.454774,193.425879,2970.424623,15.568090,76.010050,1.572864
std,7.815984,1.701004,104.269838,846.841774,2.757689,3.697627,0.802055
min,9.000000,3.000000,68.000000,1613.000000,8.000000,70.000000,1.000000
25%,17.500000,4.000000,104.250000,2223.750000,13.825000,73.000000,1.000000
50%,23.000000,4.000000,148.500000,2803.500000,15.500000,76.000000,1.000000
75%,29.000000,8.000000,262.000000,3608.000000,17.175000,79.000000,2.000000
max,46.600000,8.000000,455.000000,5140.000000,24.800000,82.000000,3.000000

In [78]:
df['car name'].unique()

array(['chevrolet chevelle malibu', 'buick skylark 320',
       'plymouth satellite', 'amc rebel sst', 'ford torino',
       'ford galaxie 500', 'chevrolet impala', 'plymouth fury iii',
       'pontiac catalina', 'amc ambassador dpl', 'dodge challenger se',
       "plymouth 'cuda 340", 'chevrolet monte carlo',
       'buick estate wagon (sw)', 'toyota corona mark ii',
       'plymouth duster', 'amc hornet', 'ford maverick', 'datsun pl510',
       'volkswagen 1131 deluxe sedan', 'peugeot 504', 'audi 100 ls',
       'saab 99e', 'bmw 2002', 'amc gremlin', 'ford f250', 'chevy c20',
       'dodge d200', 'hi 1200d', 'chevrolet vega 2300', 'toyota corona',
       'ford pinto', 'plymouth satellite custom', 'ford torino 500',
       'amc matador', 'pontiac catalina brougham', 'dodge monaco (sw)',
       'ford country squire (sw)', 'pontiac safari (sw)',
       'amc hornet sportabout (sw)', 'chevrolet vega (sw)',
       'pontiac firebird', 'ford mustang', 'mercury capri 2000',
       'opel 1900', 'peugeot 304', 'fiat 124b', 'toyota corolla 1200',
       'datsun 1200', 'volkswagen model 111', 'plymouth cricket',
       'toyota corona hardtop', 'dodge colt hardtop', 'volkswagen type 3',
       'chevrolet vega', 'ford pinto runabout', 'amc ambassador sst',
       'mercury marquis', 'buick lesabre custom',
       'oldsmobile delta 88 royale', 'chrysler newport royal',
       'mazda rx2 coupe', 'amc matador (sw)',
       'chevrolet chevelle concours (sw)', 'ford gran torino (sw)',
       'plymouth satellite custom (sw)', 'volvo 145e (sw)',
       'volkswagen 411 (sw)', 'peugeot 504 (sw)', 'renault 12 (sw)',
       'ford pinto (sw)', 'datsun 510 (sw)',
       'toyouta corona mark ii (sw)', 'dodge colt (sw)',
       'toyota corolla 1600 (sw)', 'buick century 350',
       'chevrolet malibu', 'ford gran torino', 'dodge coronet custom',
       'mercury marquis brougham', 'chevrolet caprice classic',
       'ford ltd', 'plymouth fury gran sedan',
       'chrysler new yorker brougham', 'buick electra 225 custom',
       'amc ambassador brougham', 'plymouth valiant',
       'chevrolet nova custom', 'volkswagen super beetle', 'ford country',
       'plymouth custom suburb', 'oldsmobile vista cruiser',
       'toyota carina', 'datsun 610', 'maxda rx3', 'mercury capri v6',
       'fiat 124 sport coupe', 'chevrolet monte carlo s',
       'pontiac grand prix', 'fiat 128', 'opel manta', 'audi 100ls',
       'volvo 144ea', 'dodge dart custom', 'saab 99le', 'toyota mark ii',
       'oldsmobile omega', 'chevrolet nova', 'datsun b210',
       'chevrolet chevelle malibu classic', 'plymouth satellite sebring',
       'buick century luxus (sw)', 'dodge coronet custom (sw)',
       'audi fox', 'volkswagen dasher', 'datsun 710', 'dodge colt',
       'fiat 124 tc', 'honda civic', 'subaru', 'fiat x1.9',
       'plymouth valiant custom', 'mercury monarch', 'chevrolet bel air',
       'plymouth grand fury', 'buick century',
       'chevroelt chevelle malibu', 'plymouth fury', 'buick skyhawk',
       'chevrolet monza 2+2', 'ford mustang ii', 'toyota corolla',
       'pontiac astro', 'volkswagen rabbit', 'amc pacer', 'volvo 244dl',
       'honda civic cvcc', 'fiat 131', 'capri ii', 'renault 12tl',
       'dodge coronet brougham', 'chevrolet chevette', 'chevrolet woody',
       'vw rabbit', 'dodge aspen se', 'ford granada ghia',
       'pontiac ventura sj', 'amc pacer d/l', 'datsun b-210', 'volvo 245',
       'plymouth volare premier v8', 'mercedes-benz 280s',
       'cadillac seville', 'chevy c10', 'ford f108', 'dodge d100',
       'honda accord cvcc', 'buick opel isuzu deluxe', 'renault 5 gtl',
       'plymouth arrow gs', 'datsun f-10 hatchback',
       'oldsmobile cutlass supreme', 'dodge monaco brougham',
       'mercury cougar brougham', 'chevrolet concours', 'buick skylark',
       'plymouth volare custom', 'ford granada', 'pontiac grand prix lj',
       'chevrolet monte carlo landau', 'chrysler cordoba',
       'ford thunderbird', 'volkswagen rabbit custom',
       'pontiac sunbird coupe', 'toyota corolla liftback',
       'ford mustang ii 2+2', 'dodge colt m/m', 'subaru dl', 'datsun 810',
       'bmw 320i', 'mazda rx-4', 'volkswagen rabbit custom diesel',
       'ford fiesta', 'mazda glc deluxe', 'datsun b210 gx',
       'oldsmobile cutlass salon brougham', 'dodge diplomat',
       'mercury monarch ghia', 'pontiac phoenix lj',
       'ford fairmont (auto)', 'ford fairmont (man)', 'plymouth volare',
       'amc concord', 'buick century special', 'mercury zephyr',
       'dodge aspen', 'amc concord d/l',
       'buick regal sport coupe (turbo)', 'ford futura',
       'dodge magnum xe', 'datsun 510', 'dodge omni',
       'toyota celica gt liftback', 'plymouth sapporo',
       'oldsmobile starfire sx', 'datsun 200-sx', 'audi 5000',
       'volvo 264gl', 'saab 99gle', 'peugeot 604sl',
       'volkswagen scirocco', 'honda accord lx', 'pontiac lemans v6',
       'mercury zephyr 6', 'ford fairmont 4', 'amc concord dl 6',
       'dodge aspen 6', 'ford ltd landau', 'mercury grand marquis',
       'dodge st. regis', 'chevrolet malibu classic (sw)',
       'chrysler lebaron town @ country (sw)', 'vw rabbit custom',
       'maxda glc deluxe', 'dodge colt hatchback custom', 'amc spirit dl',
       'mercedes benz 300d', 'cadillac eldorado', 'plymouth horizon',
       'plymouth horizon tc3', 'datsun 210', 'fiat strada custom',
       'buick skylark limited', 'chevrolet citation',
       'oldsmobile omega brougham', 'pontiac phoenix',
       'toyota corolla tercel', 'datsun 310', 'ford fairmont',
       'audi 4000', 'toyota corona liftback', 'mazda 626',
       'datsun 510 hatchback', 'mazda glc', 'vw rabbit c (diesel)',
       'vw dasher (diesel)', 'audi 5000s (diesel)', 'mercedes-benz 240d',
       'honda civic 1500 gl', 'renault lecar deluxe', 'vokswagen rabbit',
       'datsun 280-zx', 'mazda rx-7 gs', 'triumph tr7 coupe',
       'ford mustang cobra', 'honda accord', 'plymouth reliant',
       'dodge aries wagon (sw)', 'toyota starlet', 'plymouth champ',
       'honda civic 1300', 'datsun 210 mpg', 'toyota tercel',
       'mazda glc 4', 'plymouth horizon 4', 'ford escort 4w',
       'ford escort 2h', 'volkswagen jetta', 'renault 18i',
       'honda prelude', 'datsun 200sx', 'peugeot 505s turbo diesel',
       'volvo diesel', 'toyota cressida', 'datsun 810 maxima',
       'oldsmobile cutlass ls', 'ford granada gl',
       'chrysler lebaron salon', 'chevrolet cavalier',
       'chevrolet cavalier wagon', 'chevrolet cavalier 2-door',
       'pontiac j2000 se hatchback', 'dodge aries se',
       'ford fairmont futura', 'amc concord dl', 'volkswagen rabbit l',
       'mazda glc custom l', 'mazda glc custom', 'plymouth horizon miser',
       'mercury lynx l', 'nissan stanza xe', 'honda civic (auto)',
       'datsun 310 gx', 'buick century limited',
       'oldsmobile cutlass ciera (diesel)', 'chrysler lebaron medallion',
       'ford granada l', 'toyota celica gt', 'dodge charger 2.2',
       'chevrolet camaro', 'ford mustang gl', 'vw pickup',
       'dodge rampage', 'ford ranger', 'chevy s-10'], dtype=object)

In [81]:
df.nunique()

mpg             129
cylinders         5
displacement     82
horsepower       94
weight          351
acceleration     95
model year       13
origin            3
car name        305
dtype: int64

In [83]:
df['car name'].value_counts()

ford pinto                    6
amc matador                   5
toyota corolla                5
ford maverick                 5
toyota corona                 4
                             ..
peugeot 604sl                 1
maxda rx3                     1
pontiac j2000 se hatchback    1
peugeot 505s turbo diesel     1
pontiac lemans v6             1
Name: car name, Length: 305, dtype: int64

In [14]:
import pandas as pd
import numpy as np
a=pd.DataFrame({"name":["amit","rahul",np.nan,"neha",np.nan,np.nan],"marks":[85,95,70,np.nan,65,np.nan],"city":["ahm","surat",np.nan,"raj","raj","surat"]})
a

    name  marks   city
0   amit   85.0    ahm
1  rahul   95.0  surat
2    NaN   70.0    NaN
3   neha    NaN    raj
4    NaN   65.0    raj
5    NaN    NaN  surat

In [15]:
a.isnull()

    name  marks   city
0  False  False  False
1  False  False  False
2   True  False   True
3  False   True  False
4   True  False  False
5   True   True  False

In [17]:
a.isnull().sum()

name     3
marks    2
city     1
dtype: int64

In [38]:
b=pd.read_csv("titanic.csv")
b

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0
...,...,...,...,...,...,...,...,...,...,...,...
1304,3,"Zabour, Miss. Hileni",female,14.5000,1,0,2665,14.4542,NaN,C,0
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.2250,NaN,C,0
1307,3,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.2250,NaN,C,0
1308,3,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.8750,NaN,S,0

In [39]:
b.shape

(1309, 11)

In [40]:
b['pclass'].unique()

array([1, 2, 3], dtype=int64)

In [41]:
b.isnull().sum()

pclass         0
name           0
sex            0
age          263
sibsp          0
parch          0
ticket         0
fare           1
cabin       1014
embarked       2
survived       0
dtype: int64

In [27]:
a=a.fillna(80)
a

    name  marks   city
0   amit   85.0    ahm
1  rahul   95.0  surat
2     80   70.0     80
3   neha   80.0    raj
4     80   65.0    raj
5     80   80.0  surat

In [42]:
a=a.fillna(a.mean())
a

    name  marks   city
0   amit   85.0    ahm
1  rahul   95.0  surat
2     80   70.0     80
3   neha   80.0    raj
4     80   65.0    raj
5     80   80.0  surat

In [46]:
b['age']=b['age'].fillna(b['age'].mean())
b

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.000000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.916700,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.000000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.000000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.000000,1,2,113781,151.5500,C22 C26,S,0
...,...,...,...,...,...,...,...,...,...,...,...
1304,3,"Zabour, Miss. Hileni",female,14.500000,1,0,2665,14.4542,NaN,C,0
1305,3,"Zabour, Miss. Thamine",female,29.881135,1,0,2665,14.4542,NaN,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.500000,0,0,2656,7.2250,NaN,C,0
1307,3,"Zakarian, Mr. Ortin",male,27.000000,0,0,2670,7.2250,NaN,C,0
1308,3,"Zimmerman, Mr. Leo",male,29.000000,0,0,315082,7.8750,NaN,S,0

In [44]:
b.isnull().sum()

pclass         0
name           0
sex            0
age            0
sibsp          0
parch          0
ticket         0
fare           1
cabin       1014
embarked       2
survived       0
dtype: int64

In [45]:
b

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.000000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.916700,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.000000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.000000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.000000,1,2,113781,151.5500,C22 C26,S,0
...,...,...,...,...,...,...,...,...,...,...,...
1304,3,"Zabour, Miss. Hileni",female,14.500000,1,0,2665,14.4542,NaN,C,0
1305,3,"Zabour, Miss. Thamine",female,29.881135,1,0,2665,14.4542,NaN,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.500000,0,0,2656,7.2250,NaN,C,0
1307,3,"Zakarian, Mr. Ortin",male,27.000000,0,0,2670,7.2250,NaN,C,0
1308,3,"Zimmerman, Mr. Leo",male,29.000000,0,0,315082,7.8750,NaN,S,0

In [47]:
b['embarked'].unique()

array(['S', 'C', nan, 'Q'], dtype=object)

In [48]:
b['emabarked']=b["embarked"].fillna(b['embarked'].mode()[0])
b

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived,emabarked
0,1,"Allen, Miss. Elisabeth Walton",female,29.000000,0,0,24160,211.3375,B5,S,1,S
1,1,"Allison, Master. Hudson Trevor",male,0.916700,1,2,113781,151.5500,C22 C26,S,1,S
2,1,"Allison, Miss. Helen Loraine",female,2.000000,1,2,113781,151.5500,C22 C26,S,0,S
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.000000,1,2,113781,151.5500,C22 C26,S,0,S
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.000000,1,2,113781,151.5500,C22 C26,S,0,S
...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,"Zabour, Miss. Hileni",female,14.500000,1,0,2665,14.4542,NaN,C,0,C
1305,3,"Zabour, Miss. Thamine",female,29.881135,1,0,2665,14.4542,NaN,C,0,C
1306,3,"Zakarian, Mr. Mapriededer",male,26.500000,0,0,2656,7.2250,NaN,C,0,C
1307,3,"Zakarian, Mr. Ortin",male,27.000000,0,0,2670,7.2250,NaN,C,0,C
1308,3,"Zimmerman, Mr. Leo",male,29.000000,0,0,315082,7.8750,NaN,S,0,S

In [49]:
b.isnull().sum()

pclass          0
name            0
sex             0
age             0
sibsp           0
parch           0
ticket          0
fare            1
cabin        1014
embarked        2
survived        0
emabarked       0
dtype: int64

In [50]:
b['cabin']=b['cabin'].fillna(method='bfill')
b.isnull().sum()

pclass        0
name          0
sex           0
age           0
sibsp         0
parch         0
ticket        0
fare          1
cabin        59
embarked      2
survived      0
emabarked     0
dtype: int64

In [51]:
b['cabin']=b['cabin'].fillna(method='ffill')
b.isnull().sum()

pclass       0
name         0
sex          0
age          0
sibsp        0
parch        0
ticket       0
fare         1
cabin        0
embarked     2
survived     0
emabarked    0
dtype: int64

In [52]:
a.dropna()

    name  marks   city
0   amit   85.0    ahm
1  rahul   95.0  surat
2     80   70.0     80
3   neha   80.0    raj
4     80   65.0    raj
5     80   80.0  surat

In [54]:
import pandas as pd
import numpy as np
c=pd.DataFrame({"name":["amit","rahul",np.nan,"neha",np.nan,np.nan],"marks":[85,95,70,np.nan,65,np.nan],"city":["ahm","surat",np.nan,"raj","raj","surat"]})
c

    name  marks   city
0   amit   85.0    ahm
1  rahul   95.0  surat
2    NaN   70.0    NaN
3   neha    NaN    raj
4    NaN   65.0    raj
5    NaN    NaN  surat

In [55]:
c.dropna()

    name  marks   city
0   amit   85.0    ahm
1  rahul   95.0  surat

In [57]:
c.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5]

In [59]:
c.dropna(how='all')

    name  marks   city
0   amit   85.0    ahm
1  rahul   95.0  surat
2    NaN   70.0    NaN
3   neha    NaN    raj
4    NaN   65.0    raj
5    NaN    NaN  surat

In [62]:
c.dropna(axis=0,how='all')

    name  marks   city
0   amit   85.0    ahm
1  rahul   95.0  surat
2    NaN   70.0    NaN
3   neha    NaN    raj
4    NaN   65.0    raj
5    NaN    NaN  surat

In [63]:
c.dropna(thresh=2)

    name  marks   city
0   amit   85.0    ahm
1  rahul   95.0  surat
3   neha    NaN    raj
4    NaN   65.0    raj

In [64]:
c.dropna(subset=['marks'])

    name  marks   city
0   amit   85.0    ahm
1  rahul   95.0  surat
2    NaN   70.0    NaN
4    NaN   65.0    raj

In [71]:
c=c.drop("marks",axis=1)
c

    name   city
0   amit    ahm
1  rahul  surat
2    NaN    NaN
3   neha    raj
4    NaN    raj
5    NaN  surat

In [74]:
c=c.drop(columns=['name','city'])
c

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5]

In [81]:
a.duplicated().sum()

0

In [79]:
a.duplicated(keep='first')

0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool

In [82]:
import pandas as pd
import numpy as np
d=pd.DataFrame({"name":["amit","rahul","amit","neha",'abc','xyz'],"marks":[85,95,70,95,65,95],"city":["ahm","surat","surat","raj","raj","surat"]})
d

    name  marks   city
0   amit     85    ahm
1  rahul     95  surat
2   amit     70  surat
3   neha     95    raj
4    abc     65    raj
5    xyz     95  surat

In [87]:
d.duplicated(keep="first")

0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool

In [90]:
d.duplicated(subset=['city','marks'])

0    False
1    False
2    False
3    False
4    False
5     True
dtype: bool

In [91]:
b

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived,emabarked
0,1,"Allen, Miss. Elisabeth Walton",female,29.000000,0,0,24160,211.3375,B5,S,1,S
1,1,"Allison, Master. Hudson Trevor",male,0.916700,1,2,113781,151.5500,C22 C26,S,1,S
2,1,"Allison, Miss. Helen Loraine",female,2.000000,1,2,113781,151.5500,C22 C26,S,0,S
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.000000,1,2,113781,151.5500,C22 C26,S,0,S
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.000000,1,2,113781,151.5500,C22 C26,S,0,S
...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,"Zabour, Miss. Hileni",female,14.500000,1,0,2665,14.4542,F38,C,0,C
1305,3,"Zabour, Miss. Thamine",female,29.881135,1,0,2665,14.4542,F38,C,0,C
1306,3,"Zakarian, Mr. Mapriededer",male,26.500000,0,0,2656,7.2250,F38,C,0,C
1307,3,"Zakarian, Mr. Ortin",male,27.000000,0,0,2670,7.2250,F38,C,0,C
1308,3,"Zimmerman, Mr. Leo",male,29.000000,0,0,315082,7.8750,F38,S,0,S

In [96]:
b

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived,emabarked
0,1,"Allen, Miss. Elisabeth Walton",female,29.000000,0,0,24160,211.3375,B5,S,1,S
1,1,"Allison, Master. Hudson Trevor",male,0.916700,1,2,113781,151.5500,C22 C26,S,1,S
2,1,"Allison, Miss. Helen Loraine",female,2.000000,1,2,113781,151.5500,C22 C26,S,0,S
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.000000,1,2,113781,151.5500,C22 C26,S,0,S
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.000000,1,2,113781,151.5500,C22 C26,S,0,S
...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,"Zabour, Miss. Hileni",female,14.500000,1,0,2665,14.4542,F38,C,0,C
1305,3,"Zabour, Miss. Thamine",female,29.881135,1,0,2665,14.4542,F38,C,0,C
1306,3,"Zakarian, Mr. Mapriededer",male,26.500000,0,0,2656,7.2250,F38,C,0,C
1307,3,"Zakarian, Mr. Ortin",male,27.000000,0,0,2670,7.2250,F38,C,0,C
1308,3,"Zimmerman, Mr. Leo",male,29.000000,0,0,315082,7.8750,F38,S,0,S

In [93]:
b.shape

(1309, 12)

In [97]:
b.dropna(subset=['age'],axis=1)

KeyError: ['age']

In [100]:
b=b.dropna(subset=['age'])

In [102]:
b.shape

(1309, 12)

In [103]:
b.drop('cabin',axis=1)

,pclass,name,sex,age,sibsp,parch,ticket,fare,embarked,survived,emabarked
0,1,"Allen, Miss. Elisabeth Walton",female,29.000000,0,0,24160,211.3375,S,1,S
1,1,"Allison, Master. Hudson Trevor",male,0.916700,1,2,113781,151.5500,S,1,S
2,1,"Allison, Miss. Helen Loraine",female,2.000000,1,2,113781,151.5500,S,0,S
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.000000,1,2,113781,151.5500,S,0,S
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.000000,1,2,113781,151.5500,S,0,S
...,...,...,...,...,...,...,...,...,...,...,...
1304,3,"Zabour, Miss. Hileni",female,14.500000,1,0,2665,14.4542,C,0,C
1305,3,"Zabour, Miss. Thamine",female,29.881135,1,0,2665,14.4542,C,0,C
1306,3,"Zakarian, Mr. Mapriededer",male,26.500000,0,0,2656,7.2250,C,0,C
1307,3,"Zakarian, Mr. Ortin",male,27.000000,0,0,2670,7.2250,C,0,C
1308,3,"Zimmerman, Mr. Leo",male,29.000000,0,0,315082,7.8750,S,0,S

In [104]:
b['pclass'].value_counts()

3    709
1    323
2    277
Name: pclass, dtype: int64

In [107]:
e=pd.DataFrame({'Maths':[80,85,90,75,85],'Science':[78,82,88,80,82],'English':[70,75,80,72,79]})
e

   Maths  Science  English
0     80       78       70
1     85       82       75
2     90       88       80
3     75       80       72
4     85       82       79

In [108]:
e.sum()

Maths      415
Science    410
English    376
dtype: int64

In [109]:
e.mean

<bound method DataFrame.mean of    Maths  Science  English
0     80       78       70
1     85       82       75
2     90       88       80
3     75       80       72
4     85       82       79>

In [110]:
e.mean()

Maths      83.0
Science    82.0
English    75.2
dtype: float64

In [111]:
e.max()

Maths      90
Science    88
English    80
dtype: int64

In [112]:
e.count()

Maths      5
Science    5
English    5
dtype: int64

In [114]:
e.corr()

            Maths   Science   English
Maths    1.000000  0.820413  0.831556
Science  0.820413  1.000000  0.865253
English  0.831556  0.865253  1.000000